name: ZIndexer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2

    - name: Cache Zig
      uses: actions/cache@v3
      with:
        path: |
          ~/.zig
          zig-out

    - name: Build project
      run: zig build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: zig-out/bin
